# Generated by Django 4.1.4 on 2022-12-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Password',
            field=models.CharField(max_length=50),
        ),
    ]
